### PR TITLE
Addition of LRI potential

### PR DESCRIPTION
**Pull request by ggarg07**
## Long Range Potential Analysis
- Krishnamoorthi
- Gopal
- -------------------------------------------------------------------------------------------------
### Introduced *lriparams.py*
- Contains the `LRIParams()` class

### Modified *prob3.py*
- Introduced argument `lri_type`
- Passed `v_lri` parameter
- Modified `propagate_array()` to include `lri_pot` matrix

### Modified *numba_osc_kernels.py*
- Modified `osc_probs_layers_kernel()` to include `lri_pot` matrix
- Modified `get_transition_matrix()`, addition of `lri_pot` with the matter hamiltonian

### Modified *numba_hostfunctions.py*
- Modified `propagate_array()`
- Modified `propagate_scalar()`
- Modified `get_transition_matrix_hostfunc()`
- Modified `get_transition_matrix()`

### Modified *numba_osc_tests.py*
- Introdudced lri parameter value for the test

### CODE REVIEW

**Review by sc458930 — APPROVED** [review]

**Comment by LeanderFischer** [comment]
Did someone actually check this? 59 files changes is a whole lot?

**Comment by sc458930** [comment]
Hi Leander, Krishnamoorthi had asked review from me. I went through their changes and approved them.

**Comment by LeanderFischer** [comment]
> Hi Leander, Krishnamoorthi had asked review from me. I went through their changes and approved them.

Ok, that's good, apart from you merging, there was no sign of an actual review. Maybe next time when you go through the changes, especially if it is this many, write a comment that you looked at them and/or what you noticed etc., so that it's documented. For small changes, this isn't super important, but for big ones, it becomes easier to trace back what happened. Thanks!

**Comment by sc458930** [comment]
Sure.

**Pull request merged**
