### PR TITLE
Deprecate duplicated prior functions

### PR DESCRIPTION
**Pull request by JanWeldert**
I deprecated some prior functions that just call other functions. In case of the ParamSet they will even yield wrong results since they don't know about the deamon flux stuff

### CODE REVIEW

**Comment by LeanderFischer** [comment]
Looks good to me, thanks for taking care of this!
I'm afraid our checks are currently broken, to make sure I'll quickly re-run them and see and then we can decide whether we can just merge.

**Comment by JanWeldert** [comment]
Checks pass again. By the way, You can re-run the checks online without making a new commit.

**Comment by LeanderFischer** [comment]
> Checks pass again. By the way, You can re-run the checks online without making a new commit.

Unfortunately, that's only true if they failed.. at least I didn't find a way to do it for successful workflows (and they were, since it's been a few weeks/months).

**Review by LeanderFischer — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
