### PR TITLE
Adding Covariance Matrices

### PR DESCRIPTION
**Pull request by BenSmithers**
Basic functionality is here - hoping to continue work on this on a branch in the IceCube PISA repo rather than my personal fork. 

What's here, now
 - Adding covariance matrices to do fits with correlated nuisance parameters 
 - Code to write and read functions to and from json files 

What's not yet fully there 
 - Creating `DerivedParam`s and defining functions in config files 
 - Serialization of the full state, including `DerivedParam`s

### CODE REVIEW

**Comment by BenSmithers** [comment]
The last two commits addressed a few bugs that I came across while using these in some fits. DerivedParams are a bit closer to serializability now

**Comment by philippeller** [comment]
This looks great! So the old parameters still are usable from within each stage as if nothing happened, but internally they are represented in the rotated form, if I understood correctly?

**Comment by BenSmithers** [comment]
> This looks great! So the old parameters still are usable from within each stage as if nothing happened, but internally they are represented in the rotated form, if I understood correctly?

That's right! It essentially turns the two Params into four. The original ones are replaced with `DerivedParam`s whose values are functions of the new, rotated, ones.

**Comment by philippeller** [comment]
Cool! Is this PR thought as WIP, or do you want to get what you have merged?

**Comment by BenSmithers** [comment]
I'd like what I have here merged!

**Comment by philippeller** [comment]
cool! I then only want to run a few checks and if they pass merge it

**Comment by philippeller** [comment]
Run come additional checks, it all looks good and will merge now

**Review by philippeller — APPROVED** [review]

**Pull request merged**
