### PR TITLE
Parse param config for log-scaling

### PR DESCRIPTION
**Pull request by atrettin**
Added the log-scaling option to the config parser and added a doc-string to the option.

### CODE REVIEW

**Comment by philippeller** [comment]
Hi. looks good. Only thing: could you rebase? All PR somehow include unrelated commits....

**Comment by atrettin** [comment]
@philippeller yes sorry I was already wondering why it is always polluted with these old commits... will do.

**Comment by atrettin** [comment]
Is it possible to rebase this PR or do I have to make a new one?

**Comment by atrettin** [comment]
Hah! I actually did it! I learned some Git today. :)

**Comment by philippeller** [comment]
perfect!

**Pull request merged**
