### PR TITLE
Analysis fix

### PR DESCRIPTION
**Pull request by mvprado0**
Fixed non-list metrics issue and included functions in stats.py to better condense some lines of code.

### CODE REVIEW

**Comment by philippeller** [comment]
Hi, could you comment how the bound guard is now needed after @atrettin bumped the scipy version which fixed the boundary issue?

**Comment by mvprado0** [comment]
Hmm that's odd. I actually didn't do anything with the bound guards. I only implemented a couple of functions found in stats.py that are completely separate and fixed the issue that arises if the user inputs a metric that is not a list. 
I see the part about bound guards that you're talking about but I'm confused why that changed. Maybe I somehow forked an older version of analysis.py? I didn't think I did...

**Comment by mvprado0** [comment]
I just rechecked and I only changed the things until line 1184. Anything after that with the bound guard I didn't touch. So I'm confused

**Comment by mvprado0** [comment]
Ok, all fixed. I reincorporated my new changes to Alex's guard bounds commit.

**Review by atrettin — APPROVED** [review]
This looks good to me now!

**Pull request merged**
